### ISSUE TITLE
"DRAFT" in secondary details always showing

### ISSUE THREAD

**Issue by debryu** [NicholasMamo/adonis-template#2]
Even when there is no \data the secondary details section is rendered with the text DRAFT (today's date).
How is it possible to remove the secondary details altogether?

**Comment by debryu** [comment]
Solved, I needed to edit the adonis cls file

**Comment by NicholasMamo** [comment]
Thanks for reporting the issue. Ideally, you shouldn't have to edit the class file. The problem is that LaTeX automatically sets the `date` variable, so the `date` is never actually empty. I'll start using a new `version` variable instead of the `date` variable.

**Comment by NicholasMamo** [comment]
Has been solved with pull request: https://github.com/NicholasMamo/adonis-template/pull/3

**Comment by NicholasMamo** [comment]
Has been solved with PR https://github.com/NicholasMamo/adonis-template/pull/3
